### ISSUE TITLE
[Insight] Sensitive data should not be present in non-parameter configuration files - in app/config/security.yml, line 13

### ISSUE THREAD

**Issue by remileblond67** [remileblond67/evpos#24]
**[in app/config/security.yml, line 13](https://github.com/remileblond67/evpos/blob/bb477e6b8e90f24a814c0b4775705134efd1ec79/app/config/security.yml#L13)**

> A sensitive data has been detected in your configuration file (`password` parameter). You should consider storing it in a single parameter file.

```

    providers:
        in_memory:
            memory:
                users:
                    user:  { password: userpass, roles: [ 'ROLE_USER', 'ROLE_MAJ' ] }
                    admin: { password: adminpass, roles: [ 'ROLE_ADMIN' ] }

    firewalls:
        main_login:
            pattern: ^/log$
```

---

_Posted from [SensioLabsInsight](https://insight.sensiolabs.com/projects/a3480016-7c43-4fbd-9d26-82b00e4aa5cd/analyses/1)_
